export const publicationsData = [
  {
    id: "1",
    type: "Research Paper",
    date: "January 10, 2025",
    title: "StochasticSplats: Stochastic Rasterization for Sorting-Free 3D Gaussian Splatting",
    authors: "EurusLabs team",
    description:
      "3D Gaussian splatting (3DGS) is a popular radiance field method, with many application-specific extensions. Most variants rely on the same core method of Gaussian splatting, they rasterize in primitive order. This ensures correct alpha compositing, but can cause rendering artifacts due to built-in approximations. Moreover, for a fixed representation, sorted rasterization is not necessarily faster. In this work, we address the above limitations by combining 3D Gaussian splatting with stochastic rasterization.",
    category: "research",
    readPaperLink: "/publications/1",
    image: "https://eurusworkflows.blob.core.windows.net/eurusworkflows/images/1.jpg",
  },
  {
    id: "2",
    type: "Research Paper",
    date: "February 22, 2025",
    title: "Latent Loop Optimization: Reducing Hallucination in Long-Context Language Models",
    authors: "EurusLabs team",
    description:
      "Long-context language models (LLMs) are increasingly deployed for tasks requiring the processing and generation of extended sequences, such as document summarization, multi-step reasoning, and open-ended story generation. However, as context length grows, these models are prone to hallucinating facts, introducing inconsistencies, and losing global narrative coherence. We introduce Latent Loop Optimization (LLO), a training-free, inference-time method that leverages a reinforcement-driven decoding loop to sample, score, and re-inject latent summaries at strategic points during generation. LLO significantly reduces hallucination rates and improves coherence across a range of long-context benchmarks, without requiring model retraining or architectural changes.",
    category: "research",
    readPaperLink: "/publications/2",
    image: "https://eurusworkflows.blob.core.windows.net/eurusworkflows/images/2.jpg",
  },
  {
    id: "3",
    type: "Research Paper",
    date: "April 5, 2025",
    title: "Progressive Prompt Detailing for Improved Alignment in Text-to-Image Generative Models",
    authors: "Aarsh Ashdhir",
    description:
      "Text-to-image generative models often struggle with long prompts detailing complex scenes, diverse objects with distinct visual characteristics. In this work, we propose SCo-PE (Stochastic Controllable Prompt Embeddings), a training-free method to improve text-to-image alignment by progressively refining the input prompt in a coarse-to-fine-grained manner.",
    category: "research",
    readPaperLink: "/publications/3",
    image: "https://eurusworkflows.blob.core.windows.net/eurusworkflows/images/3.jpg",
  },
  {
    id: "4",
    type: "Research Paper",
    date: "May 18, 2025",
    title: "Sparse Causality Guidance: Improving Multi-Agent Reasoning in Generative AI",
    authors: "EurusLabs team",
    description:
      "Multi-agent generative AI systems often falter when required to reason over sparse, multi-step causal chains. This report introduces Sparse Causality Guidance (SCG)—a training-free, inference-time method that progressively injects causal structure into the generation process.",
    category: "research",
    readPaperLink: "/publications/4",
    image: "https://eurusworkflows.blob.core.windows.net/eurusworkflows/images/4.jpg",
  },
  {
    id: "7",
    type: "Blog Post",
    date: "February 2, 2025",
    title: "The Complete Guide to Visual Prompts in Eurus Studio",
    authors: "EurusLabs team",
    description:
      "A comprehensive guide to crafting effective visual prompts in Eurus Studio, covering subject definition, style direction, action, context, technical specs, and advanced prompting techniques.",
    category: "blog",
    readPaperLink: "/publications/7",
    image: "/images/blog1.jpg",
  },
  {
    id: "8",
    type: "Blog Post",
    date: "March 12, 2025",
    title: "Understanding Nodes: The Building Blocks of Creative Excellence",
    authors: "EurusLabs team",
    description:
      "Explore Eurus Studio's node-based architecture, modular creativity, node categories, advanced techniques, and workflow design for creative excellence.",
    category: "blog",
    readPaperLink: "/publications/8",
    image: "/images/blog2.jpg",
  },
  {
    id: "9",
    type: "Blog Post",
    date: "April 8, 2025",
    title: "Digital Direction: Mastering Model Posing and Expression",
    authors: "EurusLabs team",
    description:
      "Master the art of digital posing and expression in Eurus Studio, including psychology, advanced techniques, professional categories, and technical excellence.",
    category: "blog",
    readPaperLink: "/publications/9",
    image: "/images/blog3.jpg",
  },
  {
    id: "10",
    type: "Blog Post",
    date: "May 1, 2025",
    title: "The Science of AI Interpretation: Understanding Your Creative Partner",
    authors: "EurusLabs team",
    description:
      "Understand how Eurus Studio's AI interprets prompts, manages context, resolves ambiguity, and how to optimize your creative partnership.",
    category: "blog",
    readPaperLink: "/publications/10",
    image: "/images/blog4.jpg",
  },
  {
    id: "11",
    type: "Blog Post",
    date: "May 28, 2025",
    title: "From Static to Cinematic: The Art of Animation in Eurus Studio",
    authors: "EurusLabs team",
    description:
      "Learn how to bring images to life with animation in Eurus Studio, covering philosophy, architecture, advanced techniques, and professional workflows.",
    category: "blog",
    readPaperLink: "/publications/11",
    image: "/images/blog5.jpg",
  },
  {
    id: "12",
    type: "Blog Post",
    date: "June 10, 2025",
    title: "Collaborative Creation: Building the Future of Team Creativity",
    authors: "EurusLabs team",
    description:
      "Discover collaborative creativity in Eurus Studio, including real-time editing, advanced workflows, team strategies, and remote collaboration excellence.",
    category: "blog",
    readPaperLink: "/publications/12",
    image: "/images/blog6.jpg",
  },
  {
    id: "13",
    type: "Blog Post",
    date: "June 22, 2025",
    title: "Seamless Integration: Connecting Eurus Studio to Your Creative Ecosystem",
    authors: "EurusLabs team",
    description:
      "Explore how Eurus Studio integrates with Figma, After Effects, Shopify, and more, enabling unified creative workflows and advanced integration techniques.",
    category: "blog",
    readPaperLink: "/publications/13",
    image: "/images/blog7.jpg",
  },
  {
    id: "14",
    type: "Blog Post",
    date: "July 1, 2025",
    title: "Custom Intelligence: Training Eurus Studio for Your Unique Vision",
    authors: "EurusLabs team",
    description:
      "Learn how to train Eurus Studio's AI for your unique creative vision, including dataset curation, style transfer, and advanced training methodologies.",
    category: "blog",
    readPaperLink: "/publications/14",
    image: "/images/blog8.jpg",
  },
  {
    id: "15",
    type: "Blog Post",
    date: "July 5, 2025",
    title: "Visual Integrity: Detecting and Correcting AI Hallucinations",
    authors: "EurusLabs team",
    description:
      "Maintain visual integrity in AI-generated imagery with detection and correction strategies for hallucinations, quality assurance, and ethical considerations.",
    category: "blog",
    readPaperLink: "/publications/15",
    image: "/images/blog9.jpg",
  },
  {
    id: "16",
    type: "Blog Post",
    date: "July 8, 2025",
    title: "Continuous Evolution: The Feedback Loop of Creative Excellence",
    authors: "EurusLabs team",
    description:
      "Understand the feedback system in Eurus Studio for continuous creative improvement, advanced feedback mechanisms, analytics, and professional standards.",
    category: "blog",
    readPaperLink: "/publications/16",
    image: "/images/blog10.jpg",
  },
  {
    id: "17",
    type: "Announcement",
    date: "July 8, 2025",
    title: "Introducing Eurus: The Future of Visual Creation Has Arrived",
    authors: "EurusLabs team",
    description:
      "Today, we are thrilled to unveil Eurus, the flagship platform from Eurus Labs—a new era in AI-powered creativity. Designed for visionaries, innovators, and teams who believe that imagination should have no boundaries, Eurus redefines what’s possible in digital content creation.",
    category: "announcements",
    readPaperLink: "/publications/17",
    image: "https://eurusworkflows.blob.core.windows.net/eurusworkflows/images/announcements%201.jpg",
  },
]
